apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: red
  name: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: red
    spec:
      containers:
      - command:
        - "/bin/bash"
        - "-x"
        - "/entrypoint/red.sh"
        image: quay.io/jclaret/reproducer
        imagePullPolicy: IfNotPresent
        name: reproducer
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - NET_BIND_SERVICE
          privileged: true
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint
